# src/WCS/CoavBundle/Resources/config/services.yml

services:

    app.admin.reservation:
       class: WCS\CoavBundle\Admin\ReservationAdmin
       tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Reservation" }
       arguments:
            - ~
            - WCS\CoavBundle\Entity\Reservation
            - ~

    app.admin.flight:
        class: WCS\CoavBundle\Admin\FlightAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Flight" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\Flight
            - ~

    app.admin.terrain:
        class: WCS\CoavBundle\Admin\TerrainAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "terrain" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\terrain
            - ~
    app.admin.planemodel:
            class: WCS\CoavBundle\Admin\PlaneModelAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Content", label: "Plane Model" }
            arguments:
                - ~
                - WCS\CoavBundle\Entity\PlaneModel
                - ~

    app.admin.user:
                    class: WCS\CoavBundle\Admin\UserAdmin
                    tags:
                        - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
                    arguments:
                        - ~
                        - WCS\CoavBundle\Entity\User
                        - ~