WCS\CoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        departure:
            type: string
            length: '4'
            unique: true
        arrival:
            type: string
            length: '4'
            unique: true
        pilot:
            type: string
            length: 255
        freeSeats:
            type: integer
        takeTime:
            type: datetime
    lifecycleCallbacks: {  }
