WCS\CoavBundle\Entity\Terrain:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\TerrainRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        iCAO:
            type: string
            length: '4'
            unique: true
        latitude:
            type: float
        longitude:
            type: float
        city:
            type: string
            length: 255
            unique: true
        country:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }

    oneToMany:
        departures:
          targetEntity: WCS\CoavBundle\Entity\Flight
          mappedBy: departure
